import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Geist 폰트를 Google Fonts CDN에서 직접 로드합니다. */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Geist+Sans:wght@100..900&family=Geist+Mono:wght@100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      {/* <body> 태그에 CSS 변수 대신 직접 폰트 패밀리를 적용합니다. */}
      <body
        style={{
          fontFamily: "'Geist Sans', sans-serif",
        }}
        className="antialiased"
      >
        {children}
      </body>
    </html>
  );
}